# Generated by Django 5.1.6 on 2025-02-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.CharField(blank=True, db_index=True, max_length=31)),
                ('is_authenticated', models.BooleanField(db_index=True)),
                ('is_superuser', models.BooleanField(db_index=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=100)),
                ('email', models.CharField(blank=True, db_index=True, max_length=100)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('path', models.CharField(db_index=True, max_length=1000)),
                ('query_string', models.CharField(db_index=True, max_length=1000)),
                ('status_code', models.IntegerField(db_index=True)),
                ('reason_phrase', models.CharField(blank=True, db_index=True, max_length=100)),
                ('request_meta_str', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Access log entries',
            },
        ),
        migrations.CreateModel(
            name='IgnoredIpPrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=31, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Ignored IP prefixes',
            },
        ),
    ]
